"""empty message

Revision ID: a52f10db49da
Revises: 1350277e4b2f
Create Date: 2017-11-18 10:10:59.885000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52f10db49da'
down_revision = '1350277e4b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'author_id')
    # ### end Alembic commands ###
